### ISSUE TITLE
Morph Relations

### ISSUE THREAD

**Issue by johannesschobel** [alakajam-team/alakajam-poc#1]
Dear @mkalam-alami ,

i just stumbled upon this repository when googling `TypeORM Morph Relations`.. And then i saw, that you have this on your ToDo-List..

I was just wondering, if you figured out how to properly achieve morphing relationships!? Could you point me to the right directions?

All the best

**Comment by mkalam-alami** [comment]
Hi Johannes,

We haven't made much progress since, but I can say TypeORM doesn't support morph relations out of the box. It seems like we'll need to use query builders to fill the gaps.

The good news is there are some directions to be found on Github like https://github.com/typeorm/typeorm/issues/1502 and https://github.com/typeorm/typeorm/issues/3099.

One thing that should help in our particular case is to trace the SQL calls from the current ORM (in our case Bookshelf). Knowing what actual queries are run under the hood should help migrating the models to TypeORM.

Good luck with your project :)

**Comment by johannesschobel** [comment]
Dear @mkalam-alami ,

thanks a lot for your answer - I know the `x_type` and `x_id` "solution" that is proposed in your linked issues from Laravel.. However, Laravel manages the hydration / dehydration of entities automatically "under the hood".

I mean, it should be ok to implement it on your own, but i thought it would be nice to have such features "out of the box" from TypeORM.. 

Thanks a lot for your time and help
